### ISSUE TITLE
目前模版引擎功能太弱，不支持计算等常用使用情形，希望后续增加模版引擎支持 Handlebars

### ISSUE THREAD

**Issue by rayl6** [ZTO-Express/tang#13]

**Comment by rayl6** [comment]
![image](https://user-images.githubusercontent.com/5249218/206094832-49cc0a23-b796-42df-8bb8-ae3a3dd66a11.png)
通过新增模版的方式，可以多种模版混合使用，大大提高模版的灵活性

**Comment by xiongz** [comment]
后续添加对过滤器的支持，类似 ${{ date | dateFormatter('YYYY-MM-DD HH:mm:ss') }} 的写法！

**Comment by rayl6** [comment]
感谢xiongz的提交，新的写法已经合到zpage最新版本里面了。

**Comment by samma835** [comment]
> 后续添加对过滤器的支持，类似 ${{ date | dateFormatter('YYYY-MM-DD HH:mm:ss') }} 的写法！

过滤器官方已经从 vue3 里面移除, 这块看看能否通过插件方式实现, 避免 zpage core 里面揉反官方设计的内容 @rayl6

**Comment by xiongz** [comment]
我们主要还是想采用低代码的方式来实现配置化，vue3只是我们的一个底层框架引擎而已，过滤器的方式可能会更直观更方便配置！
