### ISSUE TITLE
文档解析引擎选型

### ISSUE THREAD

**Issue by alanluo888** [ZTO-Express/tang#5]
tang使用哪个文档解析引擎？ raml-parser?  swagger-parser?  各有什么好处？ 欢迎讨论

**Comment by winterbesos** [comment]
raml-parser是解析raml格式的文档
raml的supporters主要是 Google IBM Microsoft Atlassian
swagger的supporters主要是 PayPal Cisco VMware AngularJS MuleSoft intuit 等
除了http相关的内容定义格式略有差异外底层均采用json schema - draft03定义对象数据结构和约束
openapi规范的定义 https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md
raml规范的定义https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md
具体更细节的对比我需要做一个更深入的调研，主要是针对raml规范的调研，下周一可以给出一份对比

**Comment by rayl6** [comment]
@winterbesos  如果我们的架构设计成插件模式的话，是不是可以都支持。另外后期我们也可以支持更多的解析器以满足不同的业务需求。目前有团队开发了IDEA插件解析jar包生成yapi文档，如果可以，是不是也考虑兼容他们，支持从jar包生成目标文档。

当然，我们可以考虑优先支持一种格式，并将它作为内置默认解析器，期待下周一winterbesos的分享。

**Comment by alanluo888** [comment]
> @winterbesos 如果我们的架构设计成插件模式的话，是不是可以都支持。另外后期我们也可以支持更多的解析器以满足不同的业务需求。目前有团队开发了IDEA插件解析jar包生成yapi文档，如果可以，是不是也考虑兼容他们，支持从jar包生成目标文档。
> 
> 当然，我们可以考虑优先支持一种格式，并将它作为内置默认解析器，期待下周一winterbsos的分享。

如果yapi都是大家在用的话， 是不是可以先做通过yapi文档生成各端的代码。 

也可以做通过jar生成 yapi文档，再从yapi文档生成各端代码。

**Comment by winterbesos** [comment]
> @winterbesos 如果我们的架构设计成插件模式的话，是不是可以都支持。另外后期我们也可以支持更多的解析器以满足不同的业务需求。目前有团队开发了IDEA插件解析jar包生成yapi文档，如果可以，是不是也考虑兼容他们，支持从jar包生成目标文档。
> 
> 当然，我们可以考虑优先支持一种格式，并将它作为内置默认解析器，期待下周一winterbesos的分享。

yapi底层应该用的也是这些规范，我那天看你演示的时候里面有个swagger对应的就是openapi，其实yapi更像是一个文档生成器，和代码生成应该不矛盾

**Comment by andersonme** [comment]
感觉现阶段主要还是根据我们的功能规划（或需求）来定义出文档描述模型，至于选yapi还是swagger不是很关键，可以后续做工具来做转换

**Comment by alanluo888** [comment]
![Tang (1)](https://user-images.githubusercontent.com/2813460/102973247-6120f600-4537-11eb-9408-fdaec7b528bb.png)

我用图描述一下， 我感觉现在比较流行的文档工具是Yapi和Swagger，那么我们是不是可以通过Yapi ， Swagger 以及其他文档规范，来生成前后端的代码。  即便Swagger 的文档是通过后端代码加annotation生成的，但是最终也是一个Swagger文档，同样可以通过tang来生成前端代码。

**Comment by alanluo888** [comment]
> 感觉现阶段主要还是根据我们的功能规划（或需求）来定义出文档描述模型，至于选yapi还是swagger不是很关键，可以后续做工具来做转换

我感觉我们不用自己定义一套文档描述标准，用现在大家用的就行了，这样后面融合起来也方便些

**Comment by rayl6** [comment]
@andersonme  非常同意，我们通过yapi或者swargger生成中间代码，然后再由中间代码生成相应的接口调用，个人希望中间代码（文档描述模型）采用json格式。这个可以考虑专门开一个关于文档描述模型的议题。

**Comment by andersonme** [comment]
> 我感觉我们不用自己定义一套文档描述标准，用现在大家用的就行了，这样后面融合起来也方便些
是的，我们可以先采用其中的一种（yapi, swagger, openapi）， 只要这种格式满足我们的需求就可以，后面如果有新功能现有文档标准不支持的话，我们可以再考虑自己扩展

**Comment by alanluo888** [comment]
> @andersonme 非常同意，我们通过yapi或者swargger生成中间代码，然后再由中间代码生成相应的接口调用，个人希望中间代码（文档描述模型）采用json格式。这个可以考虑专门开一个关于文档描述模型的议题。

中间代码选型的话， @winterbesos 下周介绍一下openapi和raml，看看哪个适合做中间文档标准。
